---
abstract: 'SQL parsing and processing engine'
author:
  - 'Jeff Zucker <jeff@vpservices.com>, Jens Rehsack <rehsack@cpan.org>'
build_requires:
  Math::BigInt: 1.88
  Math::Complex: 1.56
  Test::Simple: 0.90
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Statement
no_index:
  directory:
    - t
    - inc
recommends:
  Math::BigInt: 1.88
  Math::Complex: 1.56
requires:
  Carp: 0
  Clone: 0.30
  Data::Dumper: 0
  Params::Util: 1.00
  Scalar::Util: 1.0
  perl: 5.008
resources:
  license: http://dev.perl.org/licenses/
  repository: https://svn.perl.org/modules/SQL-Statement/trunk/
  x_MailingList: mailto:dbi-dev@perl.org
version: 1.402
